- name: determine swarm status
  shell: >
        docker info | egrep '^Swarm: ' | cut -d ' ' -f2
  register: swarm_status
  tags: [swarm]

# - name: join worker nodes to cluster
#   shell: "docker swarm  join   --token {{ swarm_worker_token.stdout }}   --advertise-addr {{ host_ip  }}  {{ swarm_master_ip }}:2377" 
#   when: "not swarm_master is defined  and  swarm_worker_token is not  defined   and  'active' not in swarm_status.stdout_lines" 
#   tags: [swarm]  

 


# - name: Swarm master is running
#   shell: "docker swarm init   --advertise-addr  {{ host_ip  }}  "
#   when: "swarm_master is defined     and  'active' not in swarm_status.stdout_lines "
#   register: swarm_init
#   tags: [swarm]

# - name: retrieve swarm manager token
#   command: docker swarm join-token -q manager
#   when:  "swarm_init is defined   and 'active'  in swarm_status.stdout_lines "
#   register:   swarm_manager_token
#   tags: [swarm]

# - name: retrieve swarm worker token
#   shell: docker swarm join-token -q worker
#   when:  "swarm_init is defined   and 'active'  in swarm_status.stdout_lines "
#   register: swarm_worker_token
#   tags: [swarm]
- name: display token(1)
  debug:
    msg: "  {{ hostvars[groups['swarm-master'][0]]['docker_swarm_worker_token'] }} "
  
  when:  "{{ hostvars[groups['swarm-master'][0]]['docker_swarm_worker_token'] is   defined }} "
  tags: [swarm]

- name: set_fact (1-1)
  set_fact:
    docker_swarm_worker_token: 1
    vv: 1
  when:  "{{ hostvars[groups['swarm-master'][0]]['docker_swarm_worker_token'] is not  defined }} "
  tags: [swarm]

- name: set_fact (1-2)
  set_fact:
    docker_swarm_worker_token:  "{{ hostvars[groups['swarm-master'][0]]['docker_swarm_worker_token'] }} "
  when:  "{{ vv is  not   defined }} "
  tags: [swarm]

- name: set_fact (2)
  set_fact:
    docker_swarm_worker_token: " {{ 1 + docker_swarm_worker_token }} "
  when:  "docker_swarm_worker_token is   defined "
  tags: [swarm]

- name: display token(2)
  debug:
    msg: "  {{ hostvars[groups['swarm-master'][0]]['docker_swarm_worker_token'] }} "
  tags: [swarm]



# - set_fact:
#     docker_swarm_manager_token: "{{ swarm_manager_token}}"
#     docker_swarm_worker_token: "{{ swarm_worker_token }}"
#   tags: [swarm]

# - name: display token
#   debug:
#     msg: " {{ docker_swarm_manager_token }}  "
#   tags: [swarm]

# - name: show docker_swarm_worker_token
#   debug:
#     msg: "System {{ inventory_hostname }} has token {{ docker_swarm_worker_token.stdout }}"
#   tags: [swarm]

# - name: join manager nodes to cluster
#   shell: "docker swarm join  --token {{ docker_swarm_worker_token }}  --advertise-addr  {{ host_ip  }}  {{ swarm_master_ip }}:2377" 
#   when: "swarm_master is defined      and  'active' not in swarm_status.stdout_lines"
#   tags: [swarm]

